FROM python:3.9-slim

WORKDIR /app

# Installing linux dependencies(if any)


# Copy the requirements.txt to the working directory which is currently set above
COPY streamlit-app-requirements.txt .


# Install the python dependencies 
RUN pip install -r streamlit-app-requirements.txt

