version : '3'

services:
  streamlit_app_dog_breed_classification:
    build:
      context: .
      dockerfile: dockerfiles/streamlit-ui-dog-classification-app/dockerfile

    image: streamlit_app_dog_breed_classification
    container_name: streamlit_app
    ports:
      - 8501:8501
    restart: always