wandb_version: 1

learning_rate:
  desc: null
  value: '0.01'
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Stanford Dog Species
epochs:
  desc: null
  value: '50'
batch_size:
  desc: null
  value: '256'
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699982984.282561
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
